@baseUrl = http://localhost:3000
@userToken =  {{authLogin.response.body.accessToken}}

### Auth Login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "Lucase@gmail.com",
    "password": "123"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/Lucase@gail.com
Authorization: Bearer {{userToken}}

### Create User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "luketa",
    "email": "lucas@email.com",
    "password": "123"
}

### Update User
# @name updateUSer
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
   "email": "Lucase@gmail.com"
}
